### ISSUE TITLE
Cannot boot Lakka on RG351M

### ISSUE THREAD

**Issue by fishman8** [libretro/Lakka-LibreELEC#1456]
I downloaded Lakka 3.3 and nightly 20210504 / 20210811  but no one can be boot up on my RG351M.
After vibrate and display the boot logo, then shows black screen and no any reaction after wait 3 mins.

I tried 8GB / 64GB SD cards, by using app Rufus on Windows or Etcher on Mac.

All of the conditions are not working.

The same method I can boot ArkOS, batocera, and 351ELEC.

Any suggestions would be greatly appreciated.

**Comment by Ntemis** [comment]
you sure you get the right image?
https://le-builds.lakka.tv/OdroidGoAdvance.arm/Lakka-OdroidGoAdvance.arm-3.3-rg351p.img.gz

**Comment by fishman8** [comment]
> you sure you get the right image?
> https://le-builds.lakka.tv/OdroidGoAdvance.arm/Lakka-OdroidGoAdvance.arm-3.3-rg351p.img.gz

Yes, I get the image from official website. I still tried the link you give me again but not lucky, still blank screen after bootloader. Sorry I don't have any log or output for you developers because it just blank screen...

**Comment by zongyuanliu-bio** [comment]
My RG351MP also can not boot for Lakka, but good for arkos and other OS. It seems that it is related to the wifi driver.

**Comment by ToKe79** [comment]
not fixing this. there is plan to port RK3326 and all the consoles (Odroid Go Advance/Super, Anbernic RG351 series, ...) to the 4.x branch in the future, so focus on the port, not fixing old bugs, sorry. As a workaround you may try to use .dtb file from 351ELEC build (helps with RG351MP at least).

I personaly was able to boot dev build on RG351P (which should be the same device, only in plastic case instead of metal case) with shipped .dtb files.
