### ISSUE TITLE
(Nintendo Switch) Lakka forced in highest resolution available in docked mode (4k 30hz) 

### ISSUE THREAD

**Issue by HappehLemons** [libretro/Lakka-LibreELEC#1527]
Right now using Lakka in docked mode on Nintendo Switch, it defaults its output to highest resolution to what's available on the device (In the case of my TV 4k30hz). How can I force Lakka to always output in 720p60hz and have my TV receive that signal? 

This makes it completely unusable, as 4k has a lot of overhead & 30hz messes up almost every game.

Editing retroarch.cfg did not force a new resolution. 

- Which version of Lakka are you using?
3.5
- What system hardware are you using?
Nintendo Switch
- What did you do?
Set:
video_fullscreen = "true"
video_fullscreen_x = "1280"
video_fullscreen_y = "720"
in retroarch.cfg
- What did you expect to happen?
The output source to be 1280x72060hz
- What happened instead?
Output source on TV was still 4k30hz

**Comment by GavinDarkglider** [comment]
That is because the resolution is set by the dock handler, we actually have a system in place already, for you to set a resolution of your choosing, just create lakka/storage/dock-hotplug.conf and put 1080x720 on the first line and save it, and your dock resolution will now be 720p, like the screen resolution. you can set that resolution to what ever you want, 1080x720 was just an example.

**Comment by GavinDarkglider** [comment]
Appearantly your tv doesnt natively support 720p. or maybe I mixed it up.... it might be 720x1080.....
