### ISSUE TITLE
[Feature Request] Option to switch between Limited and Full range RGB

### ISSUE THREAD

**Issue by silentJET85** [libretro/Lakka-LibreELEC#1535]
It would be very useful to have an option to change between Limited (16-235) and Full (0-255) range RGB.
My PC outputs full range by default, which looks wrong on my TV which expects Limited.

Intel and AMD drivers can change this setting by altering some configuration files. But as far as I can tell, this is not possible with the Nouveau driver.

Libreelec/Kodi has an option to compensate for this, so maybe Lakka could do something similar?

**Comment by awe444** [comment]
If/when this request gets implemented, I have an add-on request.

My understanding is that the solution might involve setting/overriding byte codes in the AVI infoframes sent over the HDMI signal. If that proves to be true, then in addition to the full/limited range RGB flag, I’d love to see aspect ratio flag overrides also implemented.

One use case would be for using standard 16:9 resolutions (720p, 1440p) as “super resolutions”, since their widths integer scale many games widths cleanly, then letting the display do the 16:9 -> 4:3 resizing.

I have a TV that obeys infoframe aspect ratio forcing from devices like GCVideo and the Retrotink 5X. For example, the Retrotink can display 720p at 4:3 using this kind of infoframe setting.

**Comment by gouchi** [comment]
It might be possible according to this [documentation](https://www.onetransistor.eu/2021/08/hdmi-picture-quantization-range-linux.html) using `proptest` but we will have to [enabled it](https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-v4.x/packages/graphics/libdrm/package.mk#L58) first.

**Comment by gouchi** [comment]
@silentJET85 Can you try to make a test with this [image](https://nightly.builds.lakka.tv/members/gouchi/1535/Lakka-Generic.x86_64-4.0-devel-20220302224739-44b31b0.img.gz) ?

Thank you.

**Comment by silentJET85** [comment]
@gouchi I don't notice any difference. Is there a setting I should be looking for?

Edit:
For what it's worth, I tried running proptest on this machine, but Nouveau doesn't seem to have the relevant options.
[proptest.txt](https://github.com/libretro/Lakka-LibreELEC/files/8181227/proptest.txt)

**Comment by gouchi** [comment]
Thank you for the test. If you don't have the option, I am afraid we can't make it work.

Maybe it is working only for Intel GPU for now with `proptest` ?

Also you should try to stop RA before doing the setup
```
systemctl stop retroarch
proptest
systemctl start retroarch
```

**Comment by silentJET85** [comment]
I see. Doing this natively seems to be impossible until the Nouveau folks decide to add that option.

However, I'm wondering if it would be possible to accomplish effectively the same thing, by somehow remapping the colors at a higher level? Possibly as a Retroarch shader?

**Comment by hizzlekizzle** [comment]
The tvout-tweaks.glsl shader has a parameter to switch to limited: https://github.com/libretro/glsl-shaders/blob/master/crt/shaders/tvout-tweaks.glsl#L21

You could try that and see if it does the trick.

**Comment by gouchi** [comment]
@silentJET85 Did you have the opportunity to make some tests ?

**Comment by silentJET85** [comment]
@gouchi I tried the tvout-tweaks shader, but it doesn't seem to make any difference. The colors are still wrong, particularly blacks are still crushed.

**Comment by gouchi** [comment]
So I am afraid this issue can't be solved right now.

You may try to make some test with Intel or AMD gpu.
