### ISSUE TITLE
Lakka 5x Bluetooth connection Problem (PS3 controller)

### ISSUE THREAD

**Issue by riyadhsheikh** [libretro/Lakka-LibreELEC#1879]
Lakka 5x Bluetooth connection Problem (PS3 controller)

**Comment by gouchi** [comment]
May you try to provide some log especially with `[createlog](https://www.lakka.tv/doc/Troubleshooting-Lakka/) ?

Otherwise, it will be difficult to make a diagnostic.

Thank you.

P.S = Please review the [issue template](https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-v5.x/.github/ISSUE_TEMPLATE.md).

**Comment by Ntemis** [comment]
no sufficient logs
