### ISSUE TITLE
Non LTS kernels?

### ISSUE THREAD

**Issue by M1cha** [libretro/Lakka-LibreELEC#1923]
I own a mini PC with an AMD 6900HX without a dedicated GPU. AMD systems are know to need very recent Linux kernel versions to work properly. The compatibility of Lakka with that system seems to provide further evidence for that:
- The current stable Lakka 4.3 with Linux 5.x does not have a GPU driver that supports this. Stuck at the flower.
- The current nightly `Lakka-Generic.x86_64-devbuild-v5.x-20240117-f0d7d16.img.gz` has Linux 6.1. This one boots([1]), but has graphical issues. I have random flickering in the "Explore" Menu. Twilight princess for NGC also has graphical artifacts like shadows flickering.

If I use archlinux(kernel 6.7) with wayland and the flatpak version of retroarch, things work perfectly. Of course, it's hard to compare these very different software setups, but it's likely that the newer kernel version plays a big role here.

So: Is there any chance you can provide Desktop versions with the latest stable Linux kernel instead of LTS versions? Otherwise we'd still have to wait many years to be able to support such recent systems.

[1] Unrelated to this issue, but the installer of that nightly "forgot" to install bootx64.efi to my SSD. I had to do that manually to get it to boot.

**Comment by ToKe79** [comment]
Hi, we usually stick to LTS kernel on PC due to stability. Kernel gets updated with each major version to the most recent LTS kernel version. Soon we may start shipping devel builds based on more recent kernel.

Regarding the installation, it is odd, the script should copy the file:
https://github.com/libretro/Lakka-LibreELEC/blob/7a8c0735103ff998d978638c0c424e3ccac0d4f0/packages/tools/installer/scripts/installer#L291-L296
