### ISSUE TITLE
how build a simple program

### ISSUE THREAD

**Issue by denisdemaisbr** [libretro/Lakka-LibreELEC#1950]
I want build a C (lua interpreter) program to run on emuelec (cross compile using linux, ubuntu).
To download at box using wget/curl and run it.

Any tips to install 'build essentials' to emuelec?

Any can help me?

**Comment by ToKe79** [comment]
first of all, you are posting to wrong repository. but since Lakka & EmuELEC have same base build system (both use LibreELEC) and the image with the root file system as read only, there is no option to install additional system software. however, you can crosscompile - just try to package what you are trying to do as a package (see [`packages/package.mk.template`](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/packages.mk.template) and this [`readme.md`](https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/readme.md).
