### ISSUE TITLE
Please Include rsync

### ISSUE THREAD

**Issue by cbluth** [libretro/Lakka-LibreELEC#289]
This issue tracker is NOT for help or support. Please use the Lakka forum (https://forums.libretro.com/c/libretro/lakka-tv-general) or IRC @ #lakka on freenode.net for those kinds of posts.

BEFORE you report a bug make sure you have tried the latest nightly version of Lakka at http://le.builds.lakka.tv/. Your bug might be already fixed.

If you are sure that it's a bug in Lakka, please answer the following questions:
- Which version of Lakka are you using?
2.1RC6
- What system hardware are you using?
s802 M8
- What did you do?
tried to use rsync
- What did you expect to happen?
rsync to be available
- What happened instead?
rsync was not available

It is important to provide logs for debugging as part of your report. Instructions for generating logs can be found in the Troubleshooting Lakka documentation at http://www.lakka.tv/doc/Troubleshooting-Lakka/

---

Please include rsync, it is very useful for transferring content over ssh. The orignal issue was found here: https://github.com/libretro/Lakka/issues/517

Here is a workaround:
Build a statically linked binary: http://www.virtuallyghetto.com/2011/02/how-to-compile-statically-linked-rsync.html

Put it in ~/.local/usr/bin/
Then I did something like this:
rsync -avPz --rsync-path=/storage/.local/usr/bin/rsync /path/ 192.168.1.12:/storage/roms/

**Comment by RobLoach** [comment]
It's included as part of `network-tools`:
https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-V2.1-dev/packages/addons/tools/network-tools/package.mk

We may need to install network-tools in the OEM package.

**Comment by cplr** [comment]
How does one install the network-tools package? I can't find any documentation on this.

**Comment by kadamwolfe** [comment]
> How does one install the network-tools package? I can't find any documentation on this.

I'm in the same boat.  Having rsync installed/included would be fantastic.

**Comment by garrison** [comment]
> How does one install the network-tools package?

From within Kodi: Add-ons -> Install from repository -> LibreELEC Add-ons -> Program add-ons -> Network Tools

**Comment by natinusala** [comment]
Kodi isn't included in Lakka though. You need to rebuild the image yourself with this package included

**Comment by WHK102** [comment]
The problem: need a package. The solution: Install a package but need install other package for install the packages, but can not install the main package beacuse lakka no have a platform for install packages without recompile all.

Realy Lakka is a linux system with ssh but whitout rsync o package manager? how to install privative drivers for specific old laptop?, how to install specific tools for remote administration?, how configure a custom output audio? realy need remount the filesystem and rebuild all into the root directories?, realy use a root user without unprivilegied process with sudo and sudoers? 

Lakka is a decapited linux system.

**Comment by gianfma** [comment]
> The problem: need a package. The solution: Install a package but need install other package for install the packages, but can not install the main package beacuse lakka no have a platform for install packages without recompile all.

I was looking for the same thing - use rsync on Lakka. I can't try it since I use debian, but if somebody using Arch compiles a binary static of Rsync, would it work on Lakka? I think it should.

**Comment by WHK102** [comment]
I tried uploading the libraries and the rsync binary from ubuntu but it caused many conflicts with the existing libraries.

**Comment by gianfma** [comment]
> I tried uploading the libraries and the rsync binary from ubuntu but it caused many conflicts with the existing libraries.

I think the only way to go is to compile a bianry static. That's meant to avoid the dependencies. I got the idea from here: https://community.broadcom.com/groups/communities/community-home/librarydocuments/viewdocument?DocumentKey=028d2d43-d20d-4a24-af1d-7b346137a72f

I downloaded the binary from there and copied it to /usr/bin, but I didn't manage to get it to run. Maybe you can try yourself and see if you manage to get it to work. Please let me know if you have better results than me.

**Comment by WHK102** [comment]
I have surfed the depths of the internet, asked linux elders for advice, and managed to get rsync to work on lakka.

The first thing to consider is that Lakka uses a file system called squashfs in read-only mode, this is mounted in a temporary directory in memory and makes the system work, in this way it maintains its integrity but also makes it difficult to make changes to the file. File System.

I use Ubuntu so the task is much easier for me, we must remember that the core of Lakka is Linux with LibreELEC.

## Step 1: Modify the file system.

We assume that we have a Lakka USB connected to the pc. The USB is mounted on `/media/whk/LAKKA/` and `SYSTEM` file is the squashfs image.

The first thing we need to do is unpack the contents of the file system in any directory on the pc:

```
whk@machine:~$ cd Downloads
whk@machine:Downloads$ mkdir lakka && cd lakka
whk@machine:Downloads/lakka$ sudo su
root@machine:Downloads/lakka# unsquashfs /media/whk/LAKKA/SYSTEM
Parallel unsquashfs: Using 8 processors
30058 inodes (36913 blocks) to write

[===========================================================/] 36913/36913 100%

created 29467 files
created 921 directories
created 591 symlinks
created 0 devices
created 0 fifos
```

We now have the lakka filesystem in our download folder:

```
root@machine:Downloads/lakka# ls -lah squashfs-root/
total 48K
drwxrwxr-x 12 whk whk 4,0K ene 21  2020 .
drwxrwxr-x  3 whk whk 4,0K dic 14 22:25 ..
lrwxrwxrwx  1 whk whk    8 ene 21  2020 bin -> /usr/bin
drwxrwxr-x  2 whk whk 4,0K ene 21  2020 dev
drwxrwxr-x 18 whk whk 4,0K dic 14 22:50 etc
drwxrwxr-x  2 whk whk 4,0K ene 21  2020 flash
lrwxrwxrwx  1 whk whk    8 ene 21  2020 lib -> /usr/lib
lrwxrwxrwx  1 whk whk    8 ene 21  2020 lib64 -> /usr/lib
lrwxrwxrwx  1 whk whk   10 ene 21  2020 media -> /var/media
drwxrwxr-x  2 whk whk 4,0K ene 21  2020 proc
drwxrwxr-x  2 whk whk 4,0K ene 21  2020 run
lrwxrwxrwx  1 whk whk    9 ene 21  2020 sbin -> /usr/sbin
drwxrwxr-x  2 whk whk 4,0K ene 21  2020 storage
drwxrwxr-x  2 whk whk 4,0K ene 21  2020 sys
drwxrwxr-x  2 whk whk 4,0K ene 21  2020 tmp
drwxrwxr-x  9 whk whk 4,0K ene 21  2020 usr
drwxrwxr-x  2 whk whk 4,0K ene 21  2020 var
```

Be careful, you should not use the symbolic links or you will end up in the file system of your pc, you should use the physical files only.


## Step 2: Edit the file system.

Now we need to edit the profiles file that `ash` uses (because lakka doesn't use `bash`):

```
root@machine:Downloads/lakka# cat squashfs-root/etc/profile
...
# read config files
  for config in /etc/profile.d/*; do
    if [ -f "$config" ] ; then
      . $config
    fi
  done
```

The default profile file loads other custom files:

```
root@machine:Downloads/lakka# ls -lah squashfs-root/etc/profile.d/
total 20K
drwxrwxr-x  2 whk whk 4,0K dic 14 22:34 .
drwxrwxr-x 18 whk whk 4,0K dic 14 22:50 ..
-rw-rw-r--  1 whk whk 1,2K ene 21  2020 52-nano.conf
-rw-rw-r--  1 whk whk  926 ene 21  2020 90-systemd.conf
-rw-rw-r--  1 whk whk 1,3K dic 14 22:34 98-busybox.conf
```

All files are almost empty except `98-busybox.conf`:

```
root@machine:Downloads/lakka# cat squashfs-root/etc/profile.d/98-busybox.conf
...
export PATH="/usr/bin:/usr/sbin"
export LD_LIBRARY_PATH="/usr/lib:/tmp/cores"
...
```

We will edit the paths and include a path for it to execute binary files from the overwritable file partition, this way we will no longer need to edit the lakka file system, because we will tell the system to use the `/storage` path by default for run binaries:

```
export PATH="/usr/bin:/usr/sbin:/storage/bin"
export LD_LIBRARY_PATH="/usr/lib:/tmp/cores:/storage/lib"
```

We have indicated the `/storage/bin` path as a source of binaries and `/storage/lib` as a source of libraries.


## Step 3: Deploy the file system.

Now we must repack the image inside the USB pendrive:

```
root@machine:Downloads/lakka# mksquashfs /home/whk/Downloads/lakka/squashfs-root/ /media/whk/LAKKA/SYSTEM -noappend -always-use-fragments
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on /media/whk/LAKKA/SYSTEM, block size 131072.
[=================================================/] 36318/36318 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments,
	compressed xattrs, compressed ids
	duplicates are removed
Filesystem size 443815.52 Kbytes (433.41 Mbytes)
	40.31% of uncompressed filesystem size (1101136.09 Kbytes)
Inode table size 290115 bytes (283.32 Kbytes)
	28.17% of uncompressed inode table size (1029880 bytes)
Directory table size 440915 bytes (430.58 Kbytes)
	37.34% of uncompressed directory table size (1180750 bytes)
Number of duplicate files found 1500
Number of inodes 30978
Number of files 29466
Number of fragments 1955
Number of symbolic links  591
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 921
Number of ids (unique uids + gids) 1
Number of uids 1
	whk (1000)
Number of gids 1
	whk (1000)
```

It is important to do all this as a root user. Finally we must write the new image integrity value in md5:

```
root@machine:Downloads/lakka# md5sum /media/whk/LAKKA/SYSTEM > /media/whk/LAKKA/SYSTEM.md5
```

And expulse you USB pendrive :D 


## Step 4: Install rsync

This will allow us to upload binary files to `/storage/bin` and upload dependencies to `/storage/lib`. Now we are going to see how to install rsync on the system and how to install any other binary in the future.

Put the USB pendrive on the old pc and run Lakka. From Settings menu and Services enable SSH. Now login into using a ssh client (the remote address can see in Main menu, Information and Network information, and user is `root` and password is `root`).

From remote pc upload the rsync binarie and libraries:

```
whk@machine:~$ ssh root@192.168.0.16
root@192.168.0.16's password: 
###########################################
# Lakka - The DIY retro emulation console #
# ...... visit http://www.lakka.tv ...... #
###########################################

Lakka (official): 2.3.2 (Generic.x86_64)
Lakka:~ # mkdir bin
Lakka:~ # mkdir lib
Lakka:~ # exit
Connection to 192.168.0.16 closed.
whk@machine:~$ ldd $(which rsync)
    linux-vdso.so.1 (0x00007ffce01f5000)
    libacl.so.1 => /lib/x86_64-linux-gnu/libacl.so.1 (0x00007f3eab3c2000)
    libpopt.so.0 => /lib/x86_64-linux-gnu/libpopt.so.0 (0x00007f3eab3b4000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3eab1c2000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f3eab47c000)
whk@machine:~$ scp /usr/bin/rsync root@192.168.0.16:/storage/bin/
whk@machine:~$ scp /lib/x86_64-linux-gnu/libacl.so.1 root@192.168.0.16:/storage/lib/
whk@machine:~$ scp /lib/x86_64-linux-gnu/libpopt.so.0 root@192.168.0.16:/storage/lib/
whk@machine:~$ scp /lib/x86_64-linux-gnu/libc.so.6 root@192.168.0.16:/storage/lib/
whk@machine:~$ scp /lib64/ld-linux-x86-64.so.2 root@192.168.0.16:/storage/lib/
whk@machine:~$ ssh root@192.168.0.16
root@192.168.0.16's password: 
###########################################
# Lakka - The DIY retro emulation console #
# ...... visit http://www.lakka.tv ...... #
###########################################

Lakka (official): 2.3.2 (Generic.x86_64)
Lakka:~ # chmod +x -R /storage/bin/
Lakka:~ # chmod +x -R /storage/lib/
Lakka:~ # ls -lah /storage/bin/
total 507
drwxr-xr-x    2 root     root        1.0K Dec 15 00:44 .
drwxr-xr-x   25 root     root        1.0K Dec 15 03:28 ..
-rwxr-xr-x    1 root     root      504.6K Dec 15 03:30 rsync
Lakka:~ # ls -lah /storage/lib/
total 2261
drwxr-xr-x    2 root     root        1.0K Dec 15 00:57 .
drwxr-xr-x   25 root     root        1.0K Dec 15 03:28 ..
-rwxr-xr-x    1 root     root      187.0K Dec 15 03:32 ld-linux-x86-64.so.2
-rwxr-xr-x    1 root     root       38.2K Dec 15 03:32 libacl.so.1
-rwxr-xr-x    1 root     root        1.9M Dec 15 03:32 libc.so.6
-rwxr-xr-x    1 root     root       50.6K Dec 15 03:32 libpopt.so.0
Lakka:~ # exit
Connection to 192.168.0.16 closed.
```

Note that I have given execution permissions to the binaries and libraries that I have uploaded (you can also use filezilla or Samba to upload everything).

And that's it, now lakka has rsync :) but for some strange reason the eprfil environment does not load from rsync but from ssh, so it is enough to load the profile manually with `--rsync-path='source /etc/profile; rsync'`.


## Step 4: Tetsing rsync

In my `download.sh` write this:

```
#!/bin/bash

IP_PC="192.168.0.16";

echo 'Downloading all';
rsync \
    --rsync-path='source /etc/profile; rsync' \
    -tvrz \
    --progress \
    --links \
    --exclude='roms/sda*' --exclude='roms/sdb*' --exclude='roms/sdc*' --exclude='roms/sdd*' \
    root@$IP_PC:/storage/ ./backup/storage/;

echo 'Finish.';
```

And run it:

```
whk@machine:Download/lakka$ ./download.sh 
Downloading all
root@192.168.0.16's password: 
receiving incremental file list
.cache/machine-id
             33 100%   32.23kB/s    0:00:00 (xfr#1, to-chk=524/550)
.cache/connman/ethernet_68b599e59065_cable/
.cache/connman/ethernet_68b599e59065_cable/data
          4,096 100%    3.91MB/s    0:00:00 (xfr#2, to-chk=514/550)
.cache/connman/ethernet_68b599e59065_cable/settings
            185 100%  180.66kB/s    0:00:00 (xfr#3, to-chk=513/550)
.cache/cores/
.cache/cores/core.!usr!bin!retroarch.1607533717.375
     90,550,272 100%   44.77MB/s    0:00:01 (xfr#4, to-chk=509/550)
.cache/cores/core.!usr!bin!retroarch.1607533841.572
     89,432,064 100%   27.40MB/s    0:00:03 (xfr#5, to-chk=508/550)
.cache/cores/core.!usr!bin!retroarch.1607989955.390
...
system/mame2016/ini/ui.ini
          1,701 100%   44.90kB/s    0:00:00 (xfr#364, to-chk=0/550)
thumbnails/

sent 7,515 bytes  received 1,707,051,104 bytes  9,563,353.61 bytes/sec
total size is 2,498,912,969  speedup is 1.46
Finish.
```

Now you can install any binary with its dependencies directly on the filesystem of the writable partition. You can also use filezilla to upload the files, just keep in mind that executable files and libraries must have execution permissions.

Using lakka with rsync, The future is now! https://img.memecdn.com/this-woman-deserves-a-nobel-prize_o_2572665.jpg

**Comment by cbluth** [comment]
@WHK102 great work, thanks!

**Comment by gianfma** [comment]
> # How to install rsync on Lakka

Awesome! Thanks for sharing. I'm an Ubuntu user as well, goingo to try to set it up soon. Out of curiosity, did you get a chance to try a static version of Rsync first?

**Comment by WHK102** [comment]
> > # How to install rsync on Lakka
> 
> Awesome! Thanks for sharing. I'm an Ubuntu user as well, goingo to try to set it up soon. Out of curiosity, did you get a chance to try a static version of Rsync first?

Not because that required recompiling each binary. It must be remembered that Lakka is available for many types of architecture and systems, so trying to recompile each tool for each case and for each architecture can be a very difficult task.

**Comment by beadon** [comment]
I understand the need for squashfs, but it would really be nice to have a package manager onboard to add things on-the-fly, rather than rebuilding / reflashing the image each time.  OpenWRT uses a 'thin' package manager 'opkg', perhaps this would be a nice way to add pre-compiled packages to systems on-the-fly ?

**Comment by yhojann-cl** [comment]
> I understand the need for squashfs, but it would really be nice to have a package manager onboard to add things on-the-fly, rather than rebuilding / reflashing the image each time. OpenWRT uses a 'thin' package manager 'opkg', perhaps this would be a nice way to add pre-compiled packages to systems on-the-fly ?

The problem is that lakka is a linux system that is designed for windows users, so it lacks any basic tools of any gnu/linux distribution.
