### ISSUE TITLE
gpd win incompatibility

### ISSUE THREAD

**Issue by marleyap** [libretro/Lakka-LibreELEC#380]
I want to inform about the incompatibility of the LAKKA OS in my device, in which laptop and hand GPD WIN, problems in which are vertical screen, audio does not work, neither wifi and bluetooth, I want to install the LAKKA OS in it, but with these problems is impossible, I would like the development to make a version fully compatible with my device, ALREADY THE SAME IS PERFECT FOR GAMES AND HAS THE SAME ARCHITECTURE OF A PC,PLEASE MAKE A FULLY COMPATIBLE VERSION WITH HIM... Thanks ya ...

**Comment by Ntemis** [comment]
Am sure i already answer this on a previous post. 
Simple answer is: Cant be done because we will not break all pc images to support your device.
If its to be supported must be done on a basis of a new project and for the new project to be started and be accomplished the device must be owned and as a final answer we don't own any gpd win devices so it  cant be done so, please either stop asking this or sent us a device to be able to port it to lakka.
