### ISSUE TITLE
Feature Request: Compatibility with the VIA nano U3500  CPU

### ISSUE THREAD

**Issue by fange26** [libretro/Lakka-LibreELEC#396]
Unable to run lakkatv due to CPU compatibility. 

http://www.cpu-world.com/CPUs/Nano/VIA-Nano%20U3500.html

**Comment by gouchi** [comment]
Hi,

[CONFIG_CPU_SUP_CENTAUR](https://github.com/torvalds/linux/blob/master/arch/x86/Kconfig.cpu#L442) is enabled for [x86_64](https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-V2.1-dev/projects/Generic/linux/linux.x86_64.conf#L442) and [i386](https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-V2.1-dev/projects/Generic/linux/linux.i386.conf#L424) which should work for [Via Nano](https://en.wikipedia.org/wiki/VIA_Nano) as it has been designed by [Centaur Technology](https://en.wikipedia.org/wiki/Centaur_Technology).

So you can't boot at all ? If you can boot please boot with `live textmode` in the boot entry and try to provide `dmesg` output and [graphic log](http://www.lakka.tv/doc/Troubleshooting-Lakka/#graphic-card-logs).

If you can't boot, did you try with another linux distribution so that we can get the output 

`cat /proc/cpuinfo`
`lspci -nnk | grep -A 3 VGA`

Thank you.

**Comment by fange26** [comment]
![img-3289](https://user-images.githubusercontent.com/33208153/36361109-fb44f2b8-155b-11e8-822d-b5fb7e5e0006.JPG)
![img-3290](https://user-images.githubusercontent.com/33208153/36361110-fbb89966-155b-11e8-8f0b-ffdc26f6d5ad.JPG)
![img-3291](https://user-images.githubusercontent.com/33208153/36361111-fc042570-155b-11e8-9e2b-3c68505f55e2.JPG)
![img-3292](https://user-images.githubusercontent.com/33208153/36361112-fc507024-155b-11e8-89d6-c571a3b5519a.JPG)

**Comment by gouchi** [comment]
Hi,

As I was afraid it is using VIA chipset which is not in a good shape on Linux but the [Openchrome team](https://lists.freedesktop.org/archives/openchrome-devel/) is making progress. As far as I know they are working on [DRM/KMS and X.org](https://cgit.freedesktop.org/openchrome/) then they will work on Mesa opengl driver. On Generic platform we are using DRM/KMS.

I am sorry but you will have another device to use Lakka.
