### ISSUE TITLE
Feature suggestion: Use overlayfs for retroarch.cfg

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka-LibreELEC#494]
Is there any reason not to use the overlayfs capability to make it easier for users to customize their retroarch.cfg?

It seems like overlayfs could be configured to look for a retroarch.cfg in some folder that is Samba-accessible. If there is such a retroarch.cfg, it will be used instead of the "built-in" version of the file.

With that approach available, users could customize their retrorach.cfg without having to gain console access in order to terminate the retroarch system service as described in the docs: http://www.lakka.tv/doc/Configuring-Lakka/

Does this idea make any sense?

**Comment by ToKe79** [comment]
retroarch.cfg is stored in /storage/.config/retroarch/ and the whole /storage/.config folder is shared via Samba, share Configfiles (/etc/samba/smb.conf, can be overriden by /storage/.config/samba.conf, sample file is provided as /storage/.config/samba.conf.sample).

This is excerpt from /etc/samba/smb.conf:
```
...
[Configfiles]
  path = /storage/.config
  available = yes
  browseable = yes
  public = yes
  writeable = yes
  root preexec = mkdir -p /storage/.config
...
```

**Comment by ToKe79** [comment]
Also, it is not very meaningful to do changes to retroarch.cfg while RetroArch is running, as RetroArch will overwrite the configuration file when exiting (manual modifications will be lost). Hence it is advised to stop the retroarch.service before doing changes to the configuration file / playlists / etc.

Note: The configuration in /etc/retroarch.cfg contains "shipping defaults". It is used only during the first run of RetroArch (when /storage/.config/retroarch.cfg is not available). The /storage mount point is the home folder of the (only) root user.

**Comment by markwkidd** [comment]
Thank you for your comments, they will help me clarify my suggestion. The point is specifically to allow the user to manually change retroarch.cfg without having to access the commandline and stop the retroarch service.

My suggestion is therefore to:
1. Allow the user to use Samba to place an "override" copy of retroarch.cfg on the Lakka device (in the same way that users are already able to override other default files, like art assets, etc)
2. When present, this override retroarch.cfg will "take precedence" over the one that is normally used by Lakka (the function of overlayfs)
3. When present, this override retroarch.cfg should not be overwritten by RetroArch upon exit. In other words the override retroarch.cfg should be considered by Lakka as read-only, although the file need not necessarily have that attribute

**Comment by ToKe79** [comment]
OverlayFS would not help here, I think. RetroArch is accessing (at start reading, at exit writing) the file /storage/.config/retroarch/retroarch.cfg. What could be possibly done, before RetroArch is started, it would be checked, if a file /storage/.config/retroarch-override.cfg exists, copy it to /retroarch/.config/retroarch/retroarch.cfg and rename it to retroarch-applied.cfg and start RetroArch. Next time user wants to override the settings, they would edit the "applied" file, save it, rename it to "override", quit RetroArch, which would trigger the check for the override file and copy it to retroarch.cfg and start RetroArch with the new settings.

Adding following to `/usr/lib/retroarch/retroarch-config` (= `packages/libretro/retroarch/scripts/retroarch-config`) should do the job:

```
RA_CFG=/storage/.config/retroarch/retroarch.cfg
RA_OVR=/storage/.config/retroarch-override.cfg
RA_APL=/storage/.config/retroarch-applied.cfg

[ -f "$RA_OVR" ] && { cp "$RA_OVR" "$RA_CFG" ; mv "$RA_OVR" $RA_APL" ; }
```

But if the user makes any configuration changes in the RA UI to the configuration, they would not be included in the "applied" file. So maybe it would make sense for the user to copy the existing configuration file (retroarch.cfg) from \\lakka\configfiles\retroarch to \\lakka\configfiles, edit it, save it, rename it to retroarch-override.cfg. In such case the "applied" file would not be needed - the script would just move RA_OVR to RA_CFG (instead of copy).

Please bear in mind that RetroArch uses the persistent (not the read only) partition for saving its configuration. Hence there is no need for the OverlayFS feature - the file is editable by design. The assets/joypads/cores are shipped in the read only partition, hence the use of OverlayFS to give the user a possibility to change these files.

**Comment by metchebe** [comment]
If I understand correctly, most of what is discussed here can be achieved with the setting:
`config_save_on_exit = "false"`
This would have to be set manually first with the retroarch service stopped.
I am testing this technique to keep persistent settings and kiosk mode always enabled.

**Comment by kivutar** [comment]
This technique makes it impossible to edit the settings using the UI.

**Comment by markwkidd** [comment]
yes, I think that was the intention of the user who originally requested
this. The request was for a more where the UI is not usable at all to
change the CFG file.

However I think disabling 'save settings on exit' already achieves
basically the same effect. Personally I'm fine to close this issue unless
someone else is still interested in proposing a PR.
