### ISSUE TITLE
[Question] Odd defaults in Lakka 2.2.1

### ISSUE THREAD

**Issue by metchebe** [libretro/Lakka-LibreELEC#608]
In Lakka 2.2.1 there are the following configuration customizations (defaults) that I find strange. First, playlist editing is disabled:
```
playlist_entry_remove = "false"
playlist_entry_rename = "false"
```
Also many things are disabled from the quick menu, including overrides (which is why I looked into this):
```
quick_menu_show_cheats = "false"
quick_menu_show_latency = "false"
quick_menu_show_overlays = "false"
quick_menu_show_rewind = "false"
quick_menu_show_save_core_overrides = "false"
quick_menu_show_save_game_overrides = "false"
quick_menu_show_undo_save_load_state = "false"
```
I'm aware that there could be a reason for this and would like to know if this is, in fact, intentional.

Thanks in advance.

**Comment by ToKe79** [comment]
It is indeed intentional - see:
https://github.com/libretro/Lakka-LibreELEC/blob/a3bbc74f5291e3155bbe0a50a478b33be7d11eb0/packages/libretro/retroarch/package.mk#L132-L140
https://github.com/libretro/Lakka-LibreELEC/blob/a3bbc74f5291e3155bbe0a50a478b33be7d11eb0/packages/libretro/retroarch/package.mk#L190-L191
Reason is to make Lakka as simple as possible (my guess, author is @kivutar). Advanced users can enable these options in (advanced) settings.
